
DATA:
  ROOT: "D:/ERP_Project/ChaLearn2016_tiny"
  TRAIN_IMG_DATA: "image_data/train_data"
  VALID_IMG_DATA: "image_data/valid_data"
  TEST_IMG_DATA: "image_data/test_data"
  TRAIN_AUD_DATA: "voice_data/voice_librosa/train_data"
  VALID_AUD_DATA: "voice_data/voice_librosa/valid_data"
  TEST_AUD_DATA: "voice_data/voice_librosa/test_data"
  TRAIN_LABEL_DATA: "annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "annotation/annotation_test.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 8
  VALID_BATCH_SIZE: 4
  NUM_WORKERS: 0
MODEL:
  NAME: "audiovisual_resnet"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [100, 200]
TRAIN:
  # TRAINER: "BiModalTrainer"
  MAX_EPOCH: 30
  OUTPUT_DIR: "D:/ERP_Project/Result/01_deep_bimodal_regression_image"
TEST:
  SAVE_DATASET_OUTPUT: "D:/ERP_Project/Result/01_deep_bimodal_regression_image"
  
